### ISSUE TITLE
Resolve Issue

### ISSUE THREAD

**Issue by bradennapier** [traycerai/community#3]
Awesome idea for a plugin, innovative and useful hopefully!

---

This is having issues with my imports since we use "paths" it doesnt seem to automatically look into directories for an "index.ts" -- i know that is an esm thing but we still transpile to commonjs so

2024-05-16 22:23:21.926 [error] cannot open file:///src/packages/utils. Detail: Unable to read file 'src/packages/utils' (Error: Unable to read file 'src/packages/utils' that is actually a directory) Error while preparing orient response:

When `src/packages/utils/index.ts` did indeed exist.

This is also the case for if there is a `folderName/index.ts` it errors saying `cannot find folderName.ts` a

**Comment by hdkshingala** [comment]
Hello @bradennapier,

Thank you for reporting the issue.

Our tech doesn't search for files in the file system and have a different mechanism for the same.

**Comment by hdkshingala** [comment]
Hello @bradennapier,

Could you please share the information requested above?
