### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by xshapira** [traycerai/community#4]
- Issue Type: `Performance`
- Extension Name: `traycer-vscode`
- Extension Version: `0.2.7`
- OS Version: `Darwin x64 21.6.0`
- VS Code version: `1.89.1`

![CleanShot 2024-05-19 at 09 44 39@2x](https://github.com/traycerai/community/assets/48856190/02fd2c45-3a06-4310-a764-185e04bf4485)

**Comment by hdkshingala** [comment]
Hello @xshapira,

Thank you for reporting the issue.

I just want to confirm if this issue has been observed with Python or any other languages as well?

Our team has observed a similar issue with Python and we are already working on fixing this.

You'll see a release coming out from our side very soon which would fix this.

**Comment by hdkshingala** [comment]
@xshapira Trayver v0.3.0 has been released, addressing the previously identified issue.

We encourage you to try the new version and provide feedback if you continue to encounter any problems.

**Comment by xshapira** [comment]
@hdkshingala Thanks! But v0.3.0 didn't solve the problem.

![CleanShot 2024-05-21 at 08 11 45@2x](https://github.com/traycerai/community/assets/48856190/a7d2e407-7431-41e6-ab5d-8420f613e5ef)

**Comment by hdkshingala** [comment]
@xshapira Sorry to hear that you are still seeing the problem.

Could you please let us know which Python Language Server you are using?

We have observed that Jedi has some performance issue which causes high CPU usage and when we use Pylance, the extension and VS Code in general works better.

Could you please give it a try with Pylance and see if that resolves this problem for you?

**Comment by xshapira** [comment]
@hdkshingala I'm always using Pylance.

**Comment by hdkshingala** [comment]
@xshapira Okay, we will re-test it on some other repositories also to see when this happens.

Is the code on which you are running the extension part of some open source repository?
If so, we can use the same to run our tests.

**Comment by xshapira** [comment]
@hdkshingala Feel free to use it to run tests:

https://github.com/xshapira/web-crawler-cli

**Comment by hdkshingala** [comment]
Thank you @xshapira for sharing the repository.

We will do the tests at our end and try to reach the bottom of it to get the resolution.

**Comment by hdkshingala** [comment]
@xshapira We have released Traycer v0.3.1 to address this problem.

We performed some tests on the above repository and it worked well. 

Could you please update the extension and let us know if you still encounter the problem?

**Comment by xshapira** [comment]
@hdkshingala Improved, but still, the extension causes a high CPU load. 

![CleanShot 2024-05-22 at 08 24 23@2x](https://github.com/traycerai/community/assets/48856190/17ee98ce-772d-4288-b9b7-3ecaedaf8555)

**Comment by hdkshingala** [comment]
@xshapira Could you please share at what stage you see the high CPU load from the extension?

I ran the profiling but running Traycer's "Analyze File" command on the `crawl.py` file multiple times and didn't come across the problem.

So if you could please give us some reproduction steps, that would help us identify further issues and fix them.

**Comment by hdkshingala** [comment]
Below is from my system and even after multiple restarts of the VS Code, I am seeing the same results:

![image](https://github.com/traycerai/community/assets/34568645/67e1459a-defb-4b4c-bbe1-570935dbbd5c)

**Comment by xshapira** [comment]
Perhaps the problem is from my end. I'll need to put my house in order and double-check my system.

**Comment by hdkshingala** [comment]
@xshapira Sure and please feel free to let us know if you come across some problem which needs to be fixed from our side.

**Comment by hdkshingala** [comment]
@xshapira Did you get a chance to check if the extension is working normally for you?

Should I close the issue now?
